orbs:
  cloudfoundry: circleci/cloudfoundry@0.1.73

version: 2.1

commands:
  install_php_extensions_cmd:
    steps:
      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0
      - run: sudo docker-php-ext-install pdo pdo_mysql

  install_laravel_application_cmd:
    steps:
      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

  install_node_components_cmd:
    steps:
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - run: npm install
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules

  test_cmd:
    steps:
      # prepare the database
      - run: touch database/database.sqlite
      - run: php artisan migrate --env=testing --database=sqlite --force

      # run tests with phpunit
      - run: ./vendor/bin/phpunit

  build:
    steps:
      - checkout
      - install_php_extensions_cmd
      - install_laravel_application_cmd
      - install_node_components_cmd
      - test_cmd

executors:
    docker-executor:
      docker:
        - image: circleci/php:7.3-node-browsers
        - image: elastic/elasticsearch:6.5.0

jobs:
  test-with-docker:
    executor: docker-executor
    steps:
      - build

workflows:
  test-with-docker:
    jobs:
      - test-with-docker:
          context: build-test

  deploy-to-govuk:
    jobs:
      - test-with-docker:
          context: govuk-paas-sandbox
      - cloudfoundry/push:
          endpoint: 'https://api.london.cloud.service.gov.uk'
          appname: architecture-catalogue
          manifest: manifest.yml
          org: DOF-DSS
          space: sandbox
          package: null
          requires:
            - test-with-docker
          filters:
            branches:
              only: develop
